### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by PHGaming121** [PurSnake/fnf-grafex-engine-update#4]
when lime test windows, it give me lots of errors
![Captura de Tela (440)](https://github.com/PurSnake/fnf-grafex-engine-update/assets/76562427/8f25e478-596c-492a-bc10-2d03d395c8d0)

**Comment by ACoolioDude** [comment]
Ah, yeah, the Flixel 5x migration, how fantastic. Well, for FlxSound use this:
`#if (flixel < "5.3.0")`
`@:access(flixel.system.FlxSound._sound)`
`#else`
`@:access(flixel.sound.FlxSound._sound)`
`#end`

**Comment by ACoolioDude** [comment]
> Ah, yeah, the Flixel 5x migration, how fantastic. Well, for FlxSound use this: `#if (flixel < "5.3.0")` `@:access(flixel.system.FlxSound._sound)` `#else` `@:access(flixel.sound.FlxSound._sound)` `#end`

Add this on ChartingState
![slika](https://github.com/PurSnake/fnf-grafex-engine-update/assets/126715034/d396bc26-8c71-4207-bc9d-1f6dd21e04ee)

**Comment by ACoolioDude** [comment]
> > Ah, yeah, the Flixel 5x migration, how fantastic. Well, for FlxSound use this: `#if (flixel < "5.3.0")` `@:access(flixel.system.FlxSound._sound)` `#else` `@:access(flixel.sound.FlxSound._sound)` `#end`
> 
> Add this on ChartingState ![slika](https://user-images.githubusercontent.com/126715034/252515198-d396bc26-8c71-4207-bc9d-1f6dd21e04ee.png)

And add this to FlxSound.hx
![slika](https://github.com/PurSnake/fnf-grafex-engine-update/assets/126715034/bcc60c5d-6713-4d62-9a19-743399624ebd)
