### ISSUE TITLE
icons with names such as zombie or creeper crash the game for me for some reason

### ISSUE THREAD

**Issue by abandonedacc2123** [PurSnake/fnf-grafex-engine-update#5]
making a minecraft mod, when the icons are named creeper, zombie, or anything like zomber creep etc, it wil lcrash the game

but if i name them bf or any other base game icon,
 then  they work flawlessly

**Comment by abandonedacc2123** [comment]
(error is a null object reference)

**Comment by moxie-coder** [comment]
> making a minecraft mod, when the icons are named creeper, zombie, or anything like zomber creep etc, it wil lcrash the game
> 
> but if i name them bf or any other base game icon, then they work flawlessly

did you make sure the icons were in the mods folder? because if you just try to place the icons and use them in the assets folder, it will not work

**Comment by abandonedacc2123** [comment]
> > making a minecraft mod, when the icons are named creeper, zombie, or anything like zomber creep etc, it wil lcrash the game
> > but if i name them bf or any other base game icon, then they work flawlessly
> 
> did you make sure the icons were in the mods folder? because if you just try to place the icons and use them in the assets folder, it will not work

im using source
